"""beParticipant

Revision ID: 129171390eb9
Revises: 31d334438f7a
Create Date: 2021-05-10 14:53:33.734122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '129171390eb9'
down_revision = '31d334438f7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('participant',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('affiliation', sa.String(length=500), nullable=False),
    sa.Column('url_key', sa.String(length=500), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['countrydb.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url_key'),
    sa.UniqueConstraint('url_key')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('participant')
    # ### end Alembic commands ###
