"""FIXPKEY

Revision ID: 1620d934155a
Revises: 6a6b2e41c882
Create Date: 2021-05-10 14:41:24.931490

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1620d934155a'
down_revision = '6a6b2e41c882'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('peserta', sa.Column('id_peserta', sa.Integer(), nullable=False))
    op.drop_column('peserta', 'id')
    op.drop_constraint('peserta_pkey', 'peserta', type_='primary')
    op.create_primary_key('peserta_pkey', 'peserta', ['id_peserta'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('peserta', sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_column('peserta', 'id_peserta')
    # ### end Alembic commands ###
