"""initial table

Revision ID: 27e5251e6ba6
Revises: 
Create Date: 2021-05-08 18:56:33.757188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27e5251e6ba6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countrydb',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('iso', sa.String(length=2), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('nicename', sa.String(length=80), nullable=False),
    sa.Column('iso3', sa.String(length=3), nullable=True),
    sa.Column('numcode', sa.Integer(), nullable=True),
    sa.Column('phonecode', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('peserta',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('affiliation', sa.String(length=500), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countrydb.id'], ),
    sa.PrimaryKeyConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('peserta')
    op.drop_table('countrydb')
    # ### end Alembic commands ###
