"""adding Id To Peserta

Revision ID: 4cdf176737b1
Revises: 3312d66fc346
Create Date: 2021-05-09 12:19:06.936005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cdf176737b1'
down_revision = '3312d66fc346'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('peserta', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.add_column('peserta', sa.Column('url_key', sa.String(length=500), nullable=False))
    op.create_unique_constraint(None, 'peserta', ['url_key'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'peserta', type_='unique')
    op.drop_column('peserta', 'url_key')
    op.drop_column('peserta', 'id')
    # ### end Alembic commands ###
