"""change foreign keyv2

Revision ID: 52829bd20042
Revises: 7f660faa2676
Create Date: 2021-05-09 13:52:03.853371

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '52829bd20042'
down_revision = '7f660faa2676'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'peserta', 'countrydb', ['country'], ['iso'])
    op.drop_column('peserta', 'country_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('peserta', sa.Column('country_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'peserta', type_='foreignkey')
    # ### end Alembic commands ###
