"""id problem v5

Revision ID: 6a6b2e41c882
Revises: da15fcb1bcd9
Create Date: 2021-05-10 14:35:45.580355

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6a6b2e41c882'
down_revision = 'da15fcb1bcd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('peserta', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_column('peserta', 'id_peserta')
    op.drop_constraint('peserta_pkey', 'peserta', type_='primary')
    op.create_primary_key('peserta_pkey', 'peserta', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('peserta', sa.Column('id_peserta', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_column('peserta', 'id')
    # ### end Alembic commands ###
