"""change foreign key

Revision ID: 7f660faa2676
Revises: 8a42ad35cf76
Create Date: 2021-05-09 13:46:12.611377

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7f660faa2676'
down_revision = '8a42ad35cf76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_countrydb_iso', table_name='countrydb')
    op.create_index(op.f('ix_countrydb_iso'), 'countrydb', ['iso'], unique=True)
    op.add_column('peserta', sa.Column('country', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'peserta', 'countrydb', ['country'], ['iso'])
    op.drop_column('peserta', 'country_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('peserta', sa.Column('country_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'peserta', type_='foreignkey')
    op.drop_column('peserta', 'country')
    op.drop_index(op.f('ix_countrydb_iso'), table_name='countrydb')
    op.create_index('ix_countrydb_iso', 'countrydb', ['iso'], unique=False)
    # ### end Alembic commands ###
