"""add unique email on participant

Revision ID: c21bec06febc
Revises: 129171390eb9
Create Date: 2021-05-10 15:30:13.308419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c21bec06febc'
down_revision = '129171390eb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'participant', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'participant', type_='unique')
    # ### end Alembic commands ###
