"""id problem v2

Revision ID: da15fcb1bcd9
Revises: 3c672b6b5e37
Create Date: 2021-05-10 14:28:28.264348

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'da15fcb1bcd9'
down_revision = '3c672b6b5e37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('peserta', sa.Column('id_peserta', sa.Integer(), nullable=False))
    op.drop_column('peserta', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('peserta', sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_column('peserta', 'id_peserta')
    # ### end Alembic commands ###
